### ISSUE TITLE
helm部署byconity后 计划调整fdb组件挂载的宿主机，修改了fdb的亲和性配置，fdb组件重新创建，但老的组件未删除

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1740]
(you don't have to strictly follow this form)

## Question
以下是byconity-deploy/chart/byconity目录中values.yaml文件中fdb相关的配置，fdb组件调度到标签为bmp-byconity的宿主机上，计划把fdb组件换到其它标签的机器上去，于是我改了affinity中service_platform的值 执行helm upgrade之后 重新创建了fdb的组件 但是老的组件依然存在, 请问下 如何配置yaml文件
fdb:
  enabled: true
  enableCliPod: true
  version: 7.1.15
  clusterSpec:
    mainContainer:
      imageConfigs:
        - { version: 7.1.15,baseImage: foundationdb/foundationdb, tag: 7.1.15 }
    sidecarContainer:
      imageConfigs:
        - { version: 7.1.15,baseImage: foundationdb/foundationdb-kubernetes-sidecar, tag: 7.1.15-1 }
    processCounts:
      stateless: 3
      log: 3
      storage: 3
    processes:
      general:
        volumeClaimTemplate:
          spec:
            storageClassName: aliyun-csi-cloud-efficiency #replace to your storageClassName
            resources:
              requests:
                storage: 20Gi
        podTemplate:
          spec:
            affinity:
               nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                     nodeSelectorTerms:
                     - matchExpressions:
                         - key: service_platform
                           operator: In
                           values:
                           - bmp-byconity
            containers:  
              - name: foundationdb
                resources:
                  requests:
                    cpu: 50m
                    memory: 200m
                  limits:
                    cpu: 1
                    memory: 1Gi

**Comment by liyinsg** [comment]
```
podTemplate:
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: service_platform
                  operator: In
                  values:
                    - <new_value>
 ```
 有时候需要手工`kubectl delete pod `删除旧的pod
