### ISSUE TITLE
k8s 部署报错，helm chart 项目是否经过测试

### ISSUE THREAD

**Issue by Nick-0314** [ByConity/ByConity#1774]
### Version
helm chart 最新
命令及报错
```
helm install byconity -n deepflow chart/byconity -f values-custom.yaml

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "FoundationDBCluster" in version "apps.foundationdb.org/v1beta2"
```

部署报错：

自定义values文件：
```
# Default values for byconity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# please replace  storageClassName
nameOverride: ""
fullnameOverride: ""

image:
  repository: byconity/byconity
  tag: stable
  imagePullPolicy: IfNotPresent

byconity:
  hdfs_address: hdfs://byconity-hdfs-namenodes:8020 # can using your own hdfs
#  if “hdfs_ha_nameservice” is configured, the “hdfs_address” configuration will be ineffective
#  hdfs_ha_nameservice: hdfs_service  # after configuring “namespace”, you need to configure the address of the namespace in “hdfs3Config” 
#  use_existing_fdb: true
#  fdb_cluster_file: byconity_fdb:Is0hBgl6iICdHuspBmhAODmD5WISXKzI@192.168.224.150:4501,192.168.226.83:4501,192.168.228.152:4501
  hdfs3Config:
    dfs.client.metrics.enable: true
    dfs.client.metrics.use_domain_socket: true
    dfs.default.blocksize: "268435456"
    dfs.read.hedge_read.interval_ms: 120
    input.connect.timeout: 10000
    input.read.max.retry: 3
    input.read.timeout: 6000
    input.write.timeout: 10000
    output.close.timeout: 256000
    output.connect.timeout: 10000
    output.default.write.retry: 3
    output.read.timeout: 120000
    output.write.timeout: 256000
    rpc.client.connect.retry: 3
    rpc.client.connect.timeout: 10000
    rpc.client.read.timeout: 20000
    rpc.client.timeout: 20000
    rpc.client.write.timeout: 20000
  
  configOverwrite:
    storage_configuration:
      cnch_default_policy: server_s3_disk_0
      disks:
        # server_hdfs_disk:
        #   path: /var/byconity/data
        #   type: hdfs
        # server_local_0:
        #   path: /var/byconity/data/
        #   type: local
        
        server_s3_disk_0:
          path: byconity0
          endpoint: https://oss-cn-beijing-internal.aliyuncs.com
          region: cn-beijing
          bucket: xxxxxxxxx
          ak_id: xxxxxxxxxx
          ak_secret: xxxxxxxx
          type: bytes3
          is_virtual_hosted_style: false

      policies:
        cnch_default_hdfs:
          volumes:
            hdfs:
              default: server_s3_disk_0
              disk: server_s3_disk_0
        # cnch_default_s3:
        #   volumes:
        #     bytes3:
        #       default: server_s3_disk_0
        #       disk: server_s3_disk_0


  ports:
    tcp: 9000
    http: 8123
    rpc: 8124
    tcpSecure: 9100
    https: 9123
    exchange: 9410
    exchangeStatus: 9510

  usersOverwrite:
    users:
      default:
        password: ""
      probe:
        password: probe

  server:
    replicas: 1
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    readiness:

    liveness:
      exec:
        command:
          - bash
          - /opt/tiger/toutiao/app/scripts/liveness-server.sh
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 20
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: pl0 #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: pl0 #replace to your storageClassName
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      # timezone: Etc/UTC

  tso:
    replicas: 1
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    configOverwrite: { }
    additionalVolumes: { }
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: pl0 #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: pl0 #replace to your storageClassName



  daemonManager:
    replicas: 1 # Please keep single instance now, daemon manager HA is WIP
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    configOverwrite: { }

  resourceManager:
    replicas: 1
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    configOverwrite: { }

  defaultWorker: &defaultWorker
    replicas: 1
    image: ""
    podAnnotations: { }
    resources: { }
    hostNetwork: false
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    imagePullSecrets: [ ]
    securityContext: { }
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: pl0 #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: pl0 #replace to your storageClassName
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      # timezone: Etc/UTC

  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 1
    - <<: *defaultWorker
      name: vw_write
      replicas: 1

  commonEnvs:
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: "metadata.name"
    - name: MY_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.uid"
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: "status.podIP"
    - name: MY_HOST_IP
      valueFrom:
        fieldRef:
          # fieldPath: "status.hostIP"
          fieldPath: "status.podIP"
    - name: CONSUL_HTTP_HOST
      valueFrom:
        fieldRef:
          fieldPath: "status.hostIP"

  additionalEnvs: [ ]

  additionalVolumes:
    volumes: [ ]
    volumeMounts: [ ]

  postStart: ""
  preStop: ""
  readiness: ""
  liveness: ""

  ingress:
    enabled: false
    className: ""
    annotations: { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: byconity-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]
    #  - secretName: byconity-example-tls
    #    hosts:
    #      - byconity-example.local

# For more detailed usage, please check fdb-kubernetes-operator API doc: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/main/docs/cluster_spec.md
fdb:
  enabled: true
  enableCliPod: true
  version: 7.1.15
  clusterSpec:
    mainContainer:
      imageConfigs:
        - { version: 7.1.15,baseImage: foundationdb/foundationdb, tag: 7.1.15 }
    sidecarContainer:
      imageConfigs:
        - { version: 7.1.15,baseImage: foundationdb/foundationdb-kubernetes-sidecar, tag: 7.1.15-1 }
    processCounts:
      stateless: 3
      log: 3
      storage: 3
    processes:
      general:
        volumeClaimTemplate:
          spec:
            storageClassName: pl0 #replace to your storageClassName
            resources:
              requests:
                storage: 20Gi
#
#    fdb:
#      clusterSpec:
#        processes:
#          general:
#            volumeClaimTemplate:
#              spec:
#                storageClassName: local-device-hdd

fdb-operator:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1
      memory: 512Mi
  image:
    repository: foundationdb/fdb-kubernetes-operator
    tag: v1.9.0
    pullPolicy: IfNotPresent

hdfs:
  enabled: false
  namenode:
    repository: gchq/hdfs
    tag: 3.2.2 # managed version
    resources: { }
    nodeSelector: { }
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: pl0 #replace to your storageClassName
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    extraEnvVars: { }
    # Example usage:
    # HADOOP_HEAPSIZE_MIN: 128m
    # hadoop.heapsize.min: 128m
  datanode:
    nodeCount: 3
    repository: gchq/hdfs
    tag: 3.2.2 # managed version
    resources: { }
    nodeSelector: { }
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: pl0
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    extraEnvVars: { }
    # Example usage:
    # HADOOP_HEAPSIZE_MIN: 128m
    # hadoop.heapsize.min: 128m
  config:
    hdfsSite:
      dfs.permissions.enabled: "false"
      dfs.namenode.datanode.registration.ip-hostname-check: "false"
  shell:
    enabled: true
    repository: gchq/hdfs
    tag: 3.2.2 # managed version
    imagePullPolicy: IfNotPresent
    imagePullSecrets: [ ]
    resources: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
  postInstallCommands: [ ]
  # - hadoop fs -mkdir -p /accumulo
  # - hadoop fs -chown accumulo /accumulo
  # - hadoop fs -chmod 700 /accumulo
  # - hadoop fs -ls /

```
