### ISSUE TITLE
物理机部署组件HOST_IP获取问题

### ISSUE THREAD

**Issue by DMCAsuna** [ByConity/ByConity#1801]
使用物理机部署测试版本0.4.2，tso，resource-manager，server，daemon-manger部署在一台机器，读写worker分别部署在另外两台机器。发现部署时组件注册的IP一直为 127.0.1.1，导致worker一直无法注册到rm
![image](https://github.com/user-attachments/assets/8309171d-4b8e-44d1-aafe-5da90ec75aa8)
![image](https://github.com/user-attachments/assets/0ebe17e6-bde4-4482-a67a-cbe38e861994)

看了issue和其他部署方式的参数后尝试了以下几种方式进行解决
1. 配置 /etc/profile 下的环境变量，添加MY_HOST_IP，无效
2. 配置 service 环境变量添加 Environment="MY_HOST_IP=XXXXX"，解决

似乎是组件注册时获取host ip有问题，不知道是逻辑问题还是只认MY_HOST_IP？为何配置 /etc/profile 下的环境变量也无效呢？

同时希望可以完善下文档，这个参数也是翻了不少issue，看K8s的部署参数才看到，浪费了很多时间，对quick start非常不友好

**Comment by kevinthfang** [comment]
感谢反馈，我们看一下这个问题

**Comment by fky2015** [comment]
请问能否提供一下物理机部署时使用的配置？（关键信息可以用其他字符替换）

可以特别关注一下 

`service_discovery` 这个配置，我猜测您使用的是 `mode: local`（此处我采用 YAML 语法）。

比如以下配置：
```
service_discovery:
  mode: local
  cluster: default
  disable_cache: false
  cache_timeout: 5
  server:
    psm: data.cnch.server
    node:
      - host: server-0
        hostname: server-0
        # ...
```
会产生 `{server-0 server-0 rpc/xxx tcp/xxx}` 的配置。也即：host 是通过 `service_discovery.xxx.node[].host` 决定的。
