### ISSUE TITLE
is it possible to delete user server and probe?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#532]
There are build-in user server and probe without password.

May I delete them? and will it cause any issues?

**Comment by dmthuc** [comment]
The probe user are for liveness check and readiness check probe. The server user as I remember correctly is use for communicating between server and worker. You may want to set password for those user

**Comment by hillbun** [comment]
@dmthuc 

what should I need to modify if Iset user of server password?

**Comment by hillbun** [comment]
in chart/byconity/files/users.yaml  file

```
  probe:
    networks:
      ip: ::/0
    password: ""
    profile: default
    quota: default
```

it is no password defined,  but inside pod of byconity-server-0 

in file  /etc/byconity/users.yaml 

```
  probe:
    networks:
      ip: ::/0
    password: probe
    profile: default
    quota: default
```

password of "probe" is applyed.  


Why?
