### ISSUE TITLE
How to auto scale vw_default and vw_write?

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#568]
I use helm chart to deploy ByConity in k8s cluster.   now vw_default and vw_write replicas is defined in  chart/byconity/values.yaml

```
  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 5
    - <<: *defaultWorker
      name: vw_write
      replicas: 2
```

How to auto scale  vw_default and vw_write？

does it support HPA?
