### ISSUE TITLE
helm chart 如何分别定义 vw-vw-default 和 vw-vw-write  的资源限制

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#578]
```
  defaultWorker: &defaultWorker
    resources:
      limits:
        cpu: 4
        memory: 4096Mi
      requests:
        cpu: 4
        memory: 4096Mi
```

chart/byconity/values.yaml   中的定义，是同时针对  vw-vw-default 和  vw-vw-write 统一生效的，有没有办法实现分别定义？

**Comment by hillbun** [comment]
```
  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 5
    - <<: *defaultWorker
      name: vw_write
      replicas: 2
```

可以在这里定义吗
