### ISSUE TITLE
disk_cache_strategies 配置没有生效

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#663]
在  /etc/byconity/worker.yaml  文件配置了
```

disk_cache_strategies:
  simple:
    lru_max_size: 184320000000
```

但是缓存盘仍然没有限额：

```
overlay          20G  4.1G   15G  22% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/root        20G  4.1G   15G  22% /etc/hosts
/dev/vdc        197G  197G  4.0K 100% /var/byconity
shm              64M     0   64M   0% /dev/shm
/dev/vdb         49G  7.0G   42G  15% /var/log/byconity
tmpfs            32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
```

/dev/vdc        197G  197G  4.0K 100% /var/byconity

请问是什么原因

**Comment by wordhardqi** [comment]
设置后, 是不是没有清理过cache? 可以删除cache后试试.

**Comment by hillbun** [comment]
@wordhardqi    @foreverneverer 

我是在 vw-vw-default 节点查看的    k8s helm 方式部署的， 版本是  byconity/byconity:0.1.2

```
/etc/byconity/cnch-config.yaml 

disk_cache_strategies:
  simple:
    lru_max_size: 184320000000
```

```
/etc/byconity/worker.yaml 

disk_cache_strategies:
  simple:
    lru_max_size: 184320000000

```

请问   vw-vw-default  是依赖哪个配置文件生效？


已经把  /var/byconity/   下的
data dictionaries_lib disk_cache disk_cache_v1 disks flags format_schemas metadata metadata_dropped metastore preprocessed_configs store tmp unique_key_index_cache user_files

目录删除过了

**Comment by wordhardqi** [comment]
worker.xml
https://github.com/ByConity/ByConity/issues/626

**Comment by hillbun** [comment]
容器版本是是不是下面这个文件？

```
/etc/byconity/worker.yaml 

disk_cache_strategies:
  simple:
    lru_max_size: 184320000000
```

我已经定义了，为何不生效？

限制的是  /var/byconity/disk_cache_v1 这个目录吗？  还是   /var/byconity/ 整个目录？

**Comment by hillbun** [comment]
```
/etc/byconity/worker.yaml 

disk_cache_strategies:
  simple:
    lru_max_size: 150000000000

```

```
8.0K    ./preprocessed_configs
75M     ./metastore
4.0K    ./dictionaries_lib
197G    ./disk_cache_v1
4.0K    ./tmp
16K     ./data
20K     ./metadata
8.0K    ./disks
4.0K    ./user_files
4.0K    ./disk_cache
16K     ./lost+found
4.0K    ./unique_key_index_cache
4.0K    ./metadata_dropped
4.0K    ./format_schemas
199M    ./store
4.0K    ./flags
```

还是爆掉了

**Comment by foreverneverer** [comment]
开启日志级别为trace，然后启动后查看这个日志：https://github.com/ByConity/ByConity/blob/26b50755b08fb7b98ee79e3cc332f0e1532be820/src/Storages/DiskCache/DiskCacheFactory.cpp#L61

确定一下实际生效的参数值

**Comment by foreverneverer** [comment]
如果配置生效的值是符合预期的，执行以下命令查看纯数据占据的大小，以排除文件索引的开销：
```sh
du -sh --apparent-size disk_cache_v1
```

**Comment by hillbun** [comment]
> 开启日志级别为trace，然后启动后查看这个日志：

请问如何开启？  @foreverneverer 


> 
> https://github.com/ByConity/ByConity/blob/26b50755b08fb7b98ee79e3cc332f0e1532be820/src/Storages/DiskCache/DiskCacheFactory.cpp#L51
> 
> 确定一下实际生效的参数值

**Comment by hillbun** [comment]
日志没有 Creating DiskCache 部分

```
/etc/byconity/worker.yaml 

logger:
  console: true
  count: 50
  errorlog: /var/log/byconity/byconity.err.log
  level: trace
  log: /var/log/byconity/byconity.log
  size: 5000M
  testlog: /var/log/byconity/byconity.test.log
```
