### ISSUE TITLE
Unable to use IRSA / credential files for S3 Disk

### ISSUE THREAD

**Issue by lazywei** [ByConity/ByConity#739]
## Bug Report

We configured our s3 disk like this
```
        server_s3_disk_0:
          type: s3
          path: byconity
          endpoint: https://s3.us-west-2.amazonaws.com
          region: us-west-2
          bucket: foo-bar
          # ak_id: n/a
          # ak_secret: n/a
          # is_virtual_hosted_style: false
          use_environment_credentials: ture
```
We didn't provide the `ak_id` and `ak_secret`, but we do specify the ServiceAccount (k8s) and associated with the AWS's IRSA iam role. The hope is we don't need to put the secret explicitly in the config files.

But it seems ByConity doesn't know how to retrieve the tokens via the provided IRSA environment variables `AWS_STS_REGIONAL_ENDPOINTS, AWS_WEB_IDENTITY_TOKEN_FILE, AWS_ROLE_ARN` etc.

When inserting the data to the workers, we got this
```
Code: 499, e.displayText() = DB::S3::S3Exception: Encounter exception when request s3, HTTP Code: 403, RemoteHost: , RequestID: -------, ExceptionName: AccessDenied, ErrorMessage: Access Denied, Extra: Could not list objects in bucket foo-bar with prefix byconity/2e57688a-6219-4f4b-ad8e-17fbf37579fd/ SQLSTATE: HY000 (version 21.8.7.1)
```

### The result you expected

We should be able to provide the access key & secret via environment variable, credential file, or AWS AssumeRole API
