### ISSUE TITLE
Code: 2005, e.displayText() = DB::Exception: 1008:[E1008]Reached timeout=30000ms @xxxxxx:8124: While executing Remote SQLSTATE: HY000 (version 21.8.7.1)

### ISSUE THREAD

**Issue by skyoct** [ByConity/ByConity#881]
### Briefly describe the bug
When querying for a relatively long time.
```
Code: 2005, e.displayText() = DB::Exception: 1008:[E1008]Reached timeout=30000ms @10.80.88.29:8124: While executing Remote SQLSTATE: HY000 (version 21.8.7.1)
```
### Version
0.2.2

**Comment by nudles** [comment]
Hi @skyoct , can you share the steps to reproduce the error or copy-paste the calling stack of the exception? Thanks!

**Comment by skyoct** [comment]
@nudles 
This appears to be a query timeout issue, and we have attempted to modify the following configurations. However, the issue still persists.

```
profiles:
  default:
    exchange_timeout_ms: 900000
    receive_timeout: 900
    send_timeout: 900
```
