### ISSUE TITLE
Is disk type local deprecated in the newest master branch

### ISSUE THREAD

**Issue by ozcelgozde** [ByConity/ByConity#969]
## Question
After building the master branch on 15th December, our previously working cluster started to fail with:
No such volume `local` in storage policy `default` SQLSTATE: HY000
We have an unused configuration like this in our values.yaml:
```
storage_configuration:
      cnch_default_policy: cnch_default_s3
      disks:
        server_local_0:
          path: /var/byconity/data/
          type: local
```
Is this deprecated?
